name: Build Workflow

on:
    pull_request:
        branches: [**]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Install dependencies
              run: |
                sudo apt update
                sudo apt-get install clang -y
                sudo apt-get install libbpf-dev
                sudo apt-get install linux-headers-$(uname -r) -y
                sudo ln -s /usr/include/x86_64-linux-gnu/asm /usr/include/asm
            - name: Install golang
              run: |
                sudo wget https://go.dev/dl/go1.22.2.linux-amd64.tar.gz
                sudo rm -rf /usr/local/go
                sudo tar -C /usr/local -xzf go1.22.2.linux-amd64.tar.gz
                export PATH=$PATH:/usr/local/go/bin
            - name: Print golang version
              run: |
                go version
